// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PowerService.proto

package PowerService;

public final class PowerServiceImpl {
  private PowerServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_turnOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_turnOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_turnOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_turnOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_turnOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_turnOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_turnOffReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_turnOffReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_cardWarningRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_cardWarningRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_cardWarningReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_cardWarningReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PowerService.proto\022\014PowerService\"#\n\023Po" +
      "wer_turnOnRequest\022\014\n\004text\030\001 \001(\t\"!\n\021Power" +
      "_turnOnReply\022\014\n\004text\030\001 \001(\t\"$\n\024Power_turn" +
      "OffRequest\022\014\n\004text\030\001 \001(\t\"\"\n\022Power_turnOf" +
      "fReply\022\014\n\004text\030\001 \001(\t\"(\n\030Power_cardWarnin" +
      "gRequest\022\014\n\004text\030\001 \001(\t\"&\n\026Power_cardWarn" +
      "ingReply\022\014\n\004text\030\001 \001(\t2\242\002\n\014PowerService\022" +
      "T\n\014Power_turnOn\022!.PowerService.Power_tur" +
      "nOnRequest\032\037.PowerService.Power_turnOnRe" +
      "ply\"\000\022W\n\rPower_turnOff\022\".PowerService.Po" +
      "wer_turnOffRequest\032 .PowerService.Power_" +
      "turnOffReply\"\000\022c\n\021Power_cardWarning\022&.Po" +
      "werService.Power_cardWarningRequest\032$.Po" +
      "werService.Power_cardWarningReply\"\000B\"\n\014P" +
      "owerServiceB\020PowerServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PowerService_Power_turnOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PowerService_Power_turnOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_turnOnRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_Power_turnOnReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PowerService_Power_turnOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_turnOnReply_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_Power_turnOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PowerService_Power_turnOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_turnOffRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_Power_turnOffReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PowerService_Power_turnOffReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_turnOffReply_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_Power_cardWarningRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PowerService_Power_cardWarningRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_cardWarningRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_Power_cardWarningReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PowerService_Power_cardWarningReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_cardWarningReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
