// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PowerService.proto

package PowerService;

public interface Power_turnOnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PowerService.Power_turnOnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
