// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PowerService.proto

package PowerService;

public interface PowerService_turnOffReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PowerService.PowerService_turnOffReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
