// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PowerService.proto

package PowerService;

public final class SmartHotelRoomImpl {
  private SmartHotelRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_PowerService_turnOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_PowerService_turnOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_PowerService_turnOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_PowerService_turnOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_PowerService_turnOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_PowerService_turnOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_PowerService_turnOffReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_PowerService_turnOffReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_cardWarningRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_cardWarningRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_Power_cardWarningReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_Power_cardWarningReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PowerService.proto\022\014PowerService\"*\n\032Po" +
      "werService_turnOnRequest\022\014\n\004text\030\001 \001(\t\"*" +
      "\n\030PowerService_turnOnReply\022\016\n\006length\030\001 \001" +
      "(\005\"+\n\033PowerService_turnOffRequest\022\014\n\004tex" +
      "t\030\001 \001(\t\"+\n\031PowerService_turnOffReply\022\016\n\006" +
      "length\030\001 \001(\005\"(\n\030Power_cardWarningRequest" +
      "\022\014\n\004text\030\001 \001(\t\"(\n\026Power_cardWarningReply" +
      "\022\016\n\006length\030\001 \001(\0052\314\002\n\014PowerService\022i\n\023Pow" +
      "erService_turnOn\022(.PowerService.PowerSer" +
      "vice_turnOnRequest\032&.PowerService.PowerS" +
      "ervice_turnOnReply\"\000\022l\n\024PowerService_tur" +
      "nOff\022).PowerService.PowerService_turnOff" +
      "Request\032\'.PowerService.PowerService_turn" +
      "OffReply\"\000\022c\n\021Power_cardWarning\022&.PowerS" +
      "ervice.Power_cardWarningRequest\032$.PowerS" +
      "ervice.Power_cardWarningReply\"\000B$\n\014Power" +
      "ServiceB\022SmartHotelRoomImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PowerService_PowerService_turnOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PowerService_PowerService_turnOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_PowerService_turnOnRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_PowerService_turnOnReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PowerService_PowerService_turnOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_PowerService_turnOnReply_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_PowerService_PowerService_turnOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PowerService_PowerService_turnOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_PowerService_turnOffRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_PowerService_turnOffReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PowerService_PowerService_turnOffReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_PowerService_turnOffReply_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_PowerService_Power_cardWarningRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PowerService_Power_cardWarningRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_cardWarningRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_PowerService_Power_cardWarningReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PowerService_Power_cardWarningReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_Power_cardWarningReply_descriptor,
        new java.lang.String[] { "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
