// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package smarthotelroom;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
