// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PowerService.proto

package smarthotelroom;

public final class SmartHotelRoomImpl {
  private SmartHotelRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  
  // ------------------- AirConService ---------------------------------
  
  // AirCon_turnOn
  static final com.google.protobuf.Descriptors.Descriptor
  internal_static_AirConService_AirCon_turnOnRequest_descriptor;
  static final com.google.protobuf.Descriptors.Descriptor
  internal_static_AirConService_AirCon_turnOnReply_descriptor;
  static final 
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_AirConService_AirCon_turnOnRequest_fieldAccessorTable;
  static final 
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_AirConService_AirCon_turnOnReply_fieldAccessorTable;
  
  //AirCon_turnUp
  static final com.google.protobuf.Descriptors.Descriptor
  internal_static_AirConService_AirCon_turnUpRequest_descriptor;
  static final com.google.protobuf.Descriptors.Descriptor
  internal_static_AirConService_AirCon_turnUpReply_descriptor;
  static final 
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_AirConService_AirCon_turnUpRequest_fieldAccessorTable;
  static final 
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_AirConService_AirCon_turnUpReply_fieldAccessorTable;
  
  // AirCon_turnDown
  static final com.google.protobuf.Descriptors.Descriptor
  internal_static_AirConService_AirCon_turnDownRequest_descriptor;
  static final com.google.protobuf.Descriptors.Descriptor
  internal_static_AirConService_AirCon_turnDownReply_descriptor;
  static final 
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_AirConService_AirCon_turnDownRequest_fieldAccessorTable;
  static final 
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_AirConService_AirCon_turnDownReply_fieldAccessorTable;
  
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerService_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerService_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PowerService.proto\022\014PowerService\"\034\n\014He" +
      "lloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017" +
      "\n\007message\030\001 \001(\t2M\n\007Greeter\022B\n\010SayHello\022\032" +
      ".PowerService.HelloRequest\032\030.PowerServic" +
      "e.HelloReply\"\000B&\n\016smarthotelroomB\022SmartH" +
      "otelRoomImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    
    // ----------------------- AirConService --------------------------------
    
    // AirCon_turnOn
    internal_static_AirConService_AirCon_turnOnRequest_descriptor = 
    		getDescriptor().getMessageTypes().get(0);
    internal_static_AirConService_AirCon_turnOnReply_descriptor = 
    		getDescriptor().getMessageTypes().get(0);
    internal_static_AirConService_AirCon_turnOnRequest_fieldAccessorTable = new
    	      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
    	        internal_static_AirConService_AirCon_turnOnRequest_descriptor,
    	        new java.lang.String[] { "Name", });
    internal_static_AirConService_AirCon_turnOnReply_fieldAccessorTable = new
  	      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
  	        internal_static_AirConService_AirCon_turnOnReply_descriptor,
  	        new java.lang.String[] { "Name", });
    
     // AirCon_turnUp
     internal_static_AirConService_AirCon_turnUpRequest_descriptor = 
    		getDescriptor().getMessageTypes().get(0);
     internal_static_AirConService_AirCon_turnUpReply_descriptor = 
    		getDescriptor().getMessageTypes().get(0);
     internal_static_AirConService_AirCon_turnUpRequest_fieldAccessorTable = new
    	      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
    	        internal_static_AirConService_AirCon_turnOnRequest_descriptor,
    	        new java.lang.String[] { "Name", });
     internal_static_AirConService_AirCon_turnUpReply_fieldAccessorTable = new
  	      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
  	        internal_static_AirConService_AirCon_turnOnReply_descriptor,
  	        new java.lang.String[] { "Name", });
     
     // AirCon_turnUp
     internal_static_AirConService_AirCon_turnDownRequest_descriptor = 
    		getDescriptor().getMessageTypes().get(0);
     internal_static_AirConService_AirCon_turnDownReply_descriptor = 
    		getDescriptor().getMessageTypes().get(0);
     internal_static_AirConService_AirCon_turnDownRequest_fieldAccessorTable = new
    	      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
    	        internal_static_AirConService_AirCon_turnDownRequest_descriptor,
    	        new java.lang.String[] { "Name", });
     internal_static_AirConService_AirCon_turnDownReply_fieldAccessorTable = new
  	      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
  	        internal_static_AirConService_AirCon_turnOnReply_descriptor,
  	        new java.lang.String[] { "Name", });
    
    internal_static_PowerService_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PowerService_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_PowerService_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PowerService_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerService_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
