// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingService.proto

package HeatingService;

public interface Heating_turnOnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingService.Heating_turnOnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
