// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingService.proto

package HeatingService;

public interface Heating_turnUpReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingService.Heating_turnUpReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
