// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingService.proto

package HeatingService;

public interface Heating_turnDownReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingService.Heating_turnDownReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
