// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingService.proto

package HeatingService;

public final class SmartHotelRoomImpl {
  private SmartHotelRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingService_Heating_turnOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingService_Heating_turnOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingService_Heating_turnOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingService_Heating_turnOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingService_Heating_turnUpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingService_Heating_turnUpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingService_Heating_turnUpReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingService_Heating_turnUpReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingService_Heating_turnDownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingService_Heating_turnDownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingService_Heating_turnDownReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingService_Heating_turnDownReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024HeatingService.proto\022\016HeatingService\"%" +
      "\n\025Heating_turnOnRequest\022\014\n\004text\030\001 \001(\t\"#\n" +
      "\023Heating_turnOnReply\022\014\n\004text\030\001 \001(\t\"%\n\025He" +
      "ating_turnUpRequest\022\014\n\004text\030\001 \001(\t\"#\n\023Hea" +
      "ting_turnUpReply\022\014\n\004text\030\001 \001(\t\"\'\n\027Heatin" +
      "g_turnDownRequest\022\014\n\004text\030\001 \001(\t\"%\n\025Heati" +
      "ng_turnDownReply\022\014\n\004text\030\001 \001(\t2\266\002\n\016Heati" +
      "ngService\022^\n\016Heating_turnOn\022%.HeatingSer" +
      "vice.Heating_turnOnRequest\032#.HeatingServ" +
      "ice.Heating_turnOnReply\"\000\022^\n\016Heating_tur" +
      "nUp\022%.HeatingService.Heating_turnUpReque" +
      "st\032#.HeatingService.Heating_turnUpReply\"" +
      "\000\022d\n\020Heating_turnDown\022\'.HeatingService.H" +
      "eating_turnDownRequest\032%.HeatingService." +
      "Heating_turnDownReply\"\000B&\n\016HeatingServic" +
      "eB\022SmartHotelRoomImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeatingService_Heating_turnOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeatingService_Heating_turnOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingService_Heating_turnOnRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_HeatingService_Heating_turnOnReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeatingService_Heating_turnOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingService_Heating_turnOnReply_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_HeatingService_Heating_turnUpRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeatingService_Heating_turnUpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingService_Heating_turnUpRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_HeatingService_Heating_turnUpReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HeatingService_Heating_turnUpReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingService_Heating_turnUpReply_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_HeatingService_Heating_turnDownRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_HeatingService_Heating_turnDownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingService_Heating_turnDownRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_HeatingService_Heating_turnDownReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_HeatingService_Heating_turnDownReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingService_Heating_turnDownReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
