// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConService.proto

package AirConditioningService;

public interface AirCon_turnDownReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConService.AirCon_turnDownReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
