// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConService.proto

package AirConditioningService;

public final class SmartHotelRoomImpl {
  private SmartHotelRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConService_AirCon_turnOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConService_AirCon_turnOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConService_AirCon_turnOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConService_AirCon_turnOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConService_AirCon_turnUpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConService_AirCon_turnUpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConService_AirCon_turnUpReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConService_AirCon_turnUpReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConService_AirCon_turnDownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConService_AirCon_turnDownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConService_AirCon_turnDownReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConService_AirCon_turnDownReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AirConService.proto\022\rAirConService\"$\n\024" +
      "AirCon_turnOnRequest\022\014\n\004text\030\001 \001(\t\"$\n\022Ai" +
      "rCon_turnOnReply\022\016\n\006length\030\001 \001(\005\"$\n\024AirC" +
      "on_turnUpRequest\022\014\n\004text\030\001 \001(\t\"$\n\022AirCon" +
      "_turnUpReply\022\016\n\006length\030\001 \001(\005\"&\n\026AirCon_t" +
      "urnDownRequest\022\014\n\004text\030\001 \001(\t\"&\n\024AirCon_t" +
      "urnDownReply\022\016\n\006length\030\001 \001(\0052\246\002\n\rAirConS" +
      "ervice\022Y\n\rAirCon_turnOn\022#.AirConService." +
      "AirCon_turnOnRequest\032!.AirConService.Air" +
      "Con_turnOnReply\"\000\022Y\n\rAirCon_turnUp\022#.Air" +
      "ConService.AirCon_turnUpRequest\032!.AirCon" +
      "Service.AirCon_turnUpReply\"\000\022_\n\017AirCon_t" +
      "urnDown\022%.AirConService.AirCon_turnDownR" +
      "equest\032#.AirConService.AirCon_turnDownRe" +
      "ply\"\000B.\n\026AirConditioningServiceB\022SmartHo" +
      "telRoomImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AirConService_AirCon_turnOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AirConService_AirCon_turnOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConService_AirCon_turnOnRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_AirConService_AirCon_turnOnReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AirConService_AirCon_turnOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConService_AirCon_turnOnReply_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_AirConService_AirCon_turnUpRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AirConService_AirCon_turnUpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConService_AirCon_turnUpRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_AirConService_AirCon_turnUpReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AirConService_AirCon_turnUpReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConService_AirCon_turnUpReply_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_AirConService_AirCon_turnDownRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AirConService_AirCon_turnDownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConService_AirCon_turnDownRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_AirConService_AirCon_turnDownReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AirConService_AirCon_turnDownReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConService_AirCon_turnDownReply_descriptor,
        new java.lang.String[] { "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
