// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConService.proto

package AirConService;

public interface AirCon_turnDownRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConService.AirCon_turnDownRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
